/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domen.Grad;
import domen.OpstaDomenskaKlasa;
import domen.Poslodavac;
import forma.FrmDialog;
import forma.FrmForma;
import forma.GlavnaForma;
import forma.IPanel;
import forma.ModForme;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;

/**
 *
 * @author User
 */
public class PnlPoslodavac extends javax.swing.JPanel implements IPanel {

    private ModForme model;

    /**
     * Creates new form KreiranjeProfilaPoslodavca
     */
    public PnlPoslodavac(ModForme model) {
        initComponents();
        pripremiFormu(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVlasnik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbGrad = new javax.swing.JComboBox<>();
        btnSacuvaj = new javax.swing.JButton();

        jLabel1.setText("Naziv kompanije:");

        jLabel2.setText("Ime i prezime vlasnika:");

        jLabel3.setText("Kontakt telefon:");

        txtVlasnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlasnikActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail adresa:");

        jLabel9.setText("Grad:");

        cbGrad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String vlasnik = txtVlasnik.getText();
        String email = txtEMail.getText();
        String naziv = txtNaziv.getText();
        String telefon = txtTelefon.getText();
        Grad g = (Grad) cbGrad.getSelectedItem();
        Poslodavac p = new Poslodavac(0, naziv, vlasnik, telefon, email, g);
        boolean val = validacija(vlasnik, email, naziv, telefon);
        if (val) {
            try {
                String poruka = Kontroler.getInstanca().unesiPoslodavca(p);
                JOptionPane.showMessageDialog(this, poruka);
                sesija.Sesija.getInstanca().getMapa().put("trenutniPoslodavac", p);
                System.out.println(p);
                if (((SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
                    return;
                }
                ((JDialog) SwingUtilities.getWindowAncestor(this)).dispose();
                (((FrmForma) SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
            } catch (NullPointerException ex) {
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno cuvanje");
                Logger.getLogger(PnlPoslodavac.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtVlasnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlasnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlasnikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cbGrad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtVlasnik;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu(ModForme model) {
        ubaciGradove();
        switch (model) {
            case unos:
                btnSacuvaj.setVisible(true);

                break;
            case izmena:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniPoslodavac"));
                btnSacuvaj.setVisible(false);

                break;
            case pregled:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutniPoslodavac"));
                btnSacuvaj.setVisible(false);

                txtEMail.setEditable(false);

                txtNaziv.setEditable(false);
                txtTelefon.setEditable(false);
                txtVlasnik.setEditable(false);
                cbGrad.setEditable(false);
                break;
        }
    }

    public ModForme getModel() {
        return model;
    }

    public void setModel(ModForme model) {
        this.model = model;
    }

    private void ubaciGradove() {
        try {
            cbGrad.removeAllItems();
            List<Grad> gradovi = kontroler.Kontroler.getInstanca().vratiSveGradove();
            for (Grad g : gradovi) {
                cbGrad.addItem(g);

            }
        } catch (IOException ex) {
            Logger.getLogger(PnlPoslodavac.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PnlPoslodavac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Poslodavac p = (Poslodavac) odk;
        if (p != null) {
            txtEMail.setText(p.getElektronskaPosta());
            txtNaziv.setText(p.getNazivKompanije());
            txtTelefon.setText(p.getKontaktTelefon());
            txtVlasnik.setText(p.getImeIPrezimeVlasnika());
            cbGrad.setSelectedItem(p.getGrad());

        }
    }

    private boolean validacija(String vlasnik, String email, String naziv, String telefon) {
        if (vlasnik.isEmpty() || email.isEmpty() || naziv.isEmpty() || telefon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;

        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Pogresan format za email adresu");
            return false;
        }
        return true;
    }

}
