/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domen.Angazovanje;
import domen.Poslodavac;
import domen.RadnoMesto;
import domen.StatusUgovora;
import domen.Student;
import forma.FrmDialog;
import forma.FrmForma;
import forma.IPanel;
import forma.ModForme;
import forma.model.ModelTabeleAngazovanje;
import forma.model.ModelTabeleRM;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class PnlPretragaAngazovanja extends javax.swing.JPanel implements IPanel {

    ModelTabeleAngazovanje model;
    Student s;
    RadnoMesto rm;

    /**
     * Creates new form PnlPretragaUgovora
     */
    public PnlPretragaAngazovanja() {
        initComponents();
        pripremiFormu();
////        btnUnos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPretrazi = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngazovanja = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnVratiSve = new javax.swing.JButton();
        btnPonistenStudent = new javax.swing.JButton();
        btnPonistiRM = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        lblTip = new javax.swing.JLabel();
        lblOd = new javax.swing.JLabel();
        lblDo = new javax.swing.JLabel();
        lblSatnica = new javax.swing.JLabel();
        lblNapojnica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImePrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblJMBG = new javax.swing.JLabel();
        btnIzborRM = new javax.swing.JButton();
        btnIzborStudenta = new javax.swing.JButton();
        cbVazeca = new javax.swing.JCheckBox();

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder("Angazovanja"));

        tblAngazovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAngazovanja);

        btnIzmeni.setText("Poništi");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnUnos.setText("Unesi novo");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        btnDetalji.setText("Prikazi detalje");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(btnUnos, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(btnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(btnUnos)
                        .addGap(16, 16, 16)
                        .addComponent(btnDetalji)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btnVratiSve.setText("Vrati sve");
        btnVratiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSveActionPerformed(evt);
            }
        });

        btnPonistenStudent.setText("Ponisti izbor studenta");
        btnPonistenStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistenStudentActionPerformed(evt);
            }
        });

        btnPonistiRM.setText("Ponisti izbor radnog mesta");
        btnPonistiRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiRMActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o radnom mestu"));

        lblNaziv.setText("Naziv kompanije:");

        lblGrad.setText("Grad:");

        lblTip.setText("Tip radnog mesta:");

        lblOd.setText("Datum od:");

        lblDo.setText("Datum do:");

        lblSatnica.setText("Satnica:");

        lblNapojnica.setText("Napojnica:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(lblGrad)
                    .addComponent(lblTip)
                    .addComponent(lblOd)
                    .addComponent(lblDo)
                    .addComponent(lblNapojnica)
                    .addComponent(lblSatnica))
                .addGap(0, 304, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaziv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSatnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblNapojnica))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o studentu"));

        lblImePrezime.setText("Ime i prezime:");

        lblDatumRodjenja.setText("Datum rodjenja:");

        lblJMBG.setText("JMBG:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImePrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDatumRodjenja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJMBG)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnIzborRM.setText("Izaberi radno mesto");
        btnIzborRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborRMActionPerformed(evt);
            }
        });

        btnIzborStudenta.setText("Izaberi studenta");
        btnIzborStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborStudentaActionPerformed(evt);
            }
        });

        cbVazeca.setText("vrati samo vazeca angazovanja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVratiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPonistiRM)
                            .addComponent(btnIzborRM, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbVazeca)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIzborStudenta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPonistenStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPonistenStudent)
                        .addGap(25, 25, 25)
                        .addComponent(cbVazeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzborRM)
                            .addComponent(btnIzborStudenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPonistiRM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPretrazi)
                            .addComponent(btnVratiSve))
                        .addGap(18, 18, 18)))
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPonistenStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistenStudentActionPerformed
        s = null;
        lblImePrezime.setText("Ime i prezime: ");
        lblDatumRodjenja.setText("Datum rodjenja: ");
        lblJMBG.setText("JMBG: ");
    }//GEN-LAST:event_btnPonistenStudentActionPerformed

    private void btnPonistiRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiRMActionPerformed

        lblDo.setText("Datum do: ");
        lblOd.setText("Datum od: ");
        lblTip.setText("Tip radnog mesta: ");
        lblSatnica.setText("Satnica: ");
        lblNapojnica.setText("Napojnica: ");

        lblNaziv.setText("Naziv: ");
        lblGrad.setText("Grad: ");
        rm = null;
    }//GEN-LAST:event_btnPonistiRMActionPerformed
    private void ponisti() {

        lblDo.setText("Datum do: ");
        lblOd.setText("Datum od: ");
        lblTip.setText("Tip radnog mesta: ");
        lblSatnica.setText("Satnica: ");
        lblNapojnica.setText("Napojnica: ");

        lblNaziv.setText("Naziv: ");
        lblGrad.setText("Grad: ");
        rm = null;
        s = null;
        lblImePrezime.setText("Ime i prezime: ");
        lblDatumRodjenja.setText("Datum rodjenja: ");
        lblJMBG.setText("JMBG: ");

    }
    private void btnIzborRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborRMActionPerformed
        PnlPretragaRadnihMesta panel = new PnlPretragaRadnihMesta();
        panel.izaberi();
        //        FrmDialog forma = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnIzborRMActionPerformed

    private void btnIzborStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborStudentaActionPerformed
        PnlPretragaStudenata panel = new PnlPretragaStudenata();
        panel.izaberi();
        //        FrmDialog forma = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnIzborStudentaActionPerformed

    private void btnVratiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSveActionPerformed
        try {
            List<Angazovanje> lista = kontroler.Kontroler.getInstanca().vratiSvaAngazovanja();
            model = new ModelTabeleAngazovanje();
            for (Angazovanje s : lista) {
                model.ubaci(s);

            }
            tblAngazovanja.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVratiSveActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        PnlAngazovanje panel = new PnlAngazovanje(ModForme.unos);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        pripremiDialog(ModForme.pregled);
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        pripremiDialog(ModForme.izmena);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        Angazovanje a = new Angazovanje();
        a.setRadnoMesto(rm);
        a.setStudent(s);
        a.setStatusUgovora(null);
        if (cbVazeca.isSelected()) {
            a.setStatusUgovora(StatusUgovora.vazeci);

        }
        List<Angazovanje> lista;
        model = new ModelTabeleAngazovanje();
        try {

            lista = kontroler.Kontroler.getInstanca().vratiAngazovanja(a);

            for (Angazovanje s : lista) {

                model.ubaci(s);
            }
            tblAngazovanja.setModel(model);
           ponisti();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnPretraziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzborRM;
    private javax.swing.JButton btnIzborStudenta;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPonistenStudent;
    private javax.swing.JButton btnPonistiRM;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnUnos;
    private javax.swing.JButton btnVratiSve;
    private javax.swing.JCheckBox cbVazeca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblDo;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JLabel lblJMBG;
    private javax.swing.JLabel lblNapojnica;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOd;
    private javax.swing.JLabel lblSatnica;
    private javax.swing.JLabel lblTip;
    private javax.swing.JPanel pnl1;
    private javax.swing.JTable tblAngazovanja;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        model = new ModelTabeleAngazovanje();
        tblAngazovanja.setModel(model);

    }

    @Override
    public void popuniPodatke() {

        s = (Student) sesija.Sesija.getInstanca().getMapa().get("trenutniStudent");
        if (s != null) {
            lblImePrezime.setText("Ime i prezime: " + s.getImeIPrezime());
            lblDatumRodjenja.setText("Datum rodjenja: " + s.getDatumRodjenja());
            lblJMBG.setText("JMBG: " + s.getJMBG());
        }
        rm = (RadnoMesto) sesija.Sesija.getInstanca().getMapa().get("trenutnoRM");
        if (rm != null) {

            lblDo.setText("Datum do: " + rm.getDatumDo());
            lblOd.setText("Datum od: " + rm.getDatumOd());
            lblTip.setText("Tip radnog mesta: " + rm.getTipRadnogMesta().getNazivTipaRadnogMesta());
            lblSatnica.setText("Satnica: " + rm.getSatnica());
            lblNapojnica.setText("Napojnica: " + rm.isMogucaNapojnica());
            Poslodavac p = rm.getPoslodavac();
            lblNaziv.setText("Naziv: " + p.getNazivKompanije());
            lblGrad.setText("Grad: " + p.getGrad().toString());

        }

        Angazovanje a = (Angazovanje) sesija.Sesija.getInstanca().getMapa().get("trenutnoAngazovanje");
        if (a != null) {
            System.out.println(a);
            model.getLista().remove(a);
            model.ubaci(a);

        }
        List<Angazovanje> lista = new LinkedList<>();
        lista = sesija.Sesija.getInstanca().getAngazovanja();
        for (Angazovanje ang : lista) {
            if (ang != null) {
                System.out.println(ang);
                model.getLista().remove(ang);
                model.ubaci(ang);
            }
        }
    }

    private void pripremiDialog(ModForme modForme) {
        if (modForme != ModForme.unos) {
            int index = tblAngazovanja.getSelectedRow();

            if (index == -1) {

                JOptionPane.showMessageDialog(this, "Morate izabrati red!");
                return;
            }
            Angazovanje rm = model.getLista().get(index);
            if (modForme == ModForme.izmena && rm.getStatusUgovora() == StatusUgovora.ponisten) {
                JOptionPane.showMessageDialog(this, "Angazovanje je vec ponisteno");
                return;
            }
            sesija.Sesija.getInstanca().getMapa().put("trenutnoAngazovanje", rm);
            PnlAngazovanje panel = new PnlAngazovanje(modForme);
            FrmDialog dialog = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
            dialog.setVisible(true);
        }

    }
}
