/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domen.Student;
import forma.FrmDialog;
import forma.FrmForma;
import forma.IPanel;
import forma.ModForme;
import forma.model.ModelTabeleStudent;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class PnlPretragaStudenata extends javax.swing.JPanel implements IPanel {

    ModelTabeleStudent model;

    /**
     * Creates new form PnlPretragaStudenta
     */
    public PnlPretragaStudenata() {
        initComponents();
        pripremiTabelu();
        btnIzbor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtImeIPrezime = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudenti = new javax.swing.JTable();
        btnIzmena = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();
        btnIzbor = new javax.swing.JButton();
        btnVratiSve = new javax.swing.JButton();

        jLabel2.setText("Ime i prezime:");

        txtImeIPrezime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeIPrezimeKeyReleased(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblStudenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudenti);

        btnIzmena.setText("Izmeni");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikaži detalje");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnUnos.setText("Unesi novog");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        btnIzbor.setText("Izaberi");
        btnIzbor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIzmena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnUnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrikazi)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzbor)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnVratiSve.setText("Vrati sve");
        btnVratiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeIPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnPretrazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVratiSve)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtImeIPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnVratiSve))
                .addGap(69, 69, 69)
                .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String imeIPrezime = txtImeIPrezime.getText();
        if (imeIPrezime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli kriterijum izbora");
            return;
        }
        Student st = new Student();
        st.setImeIPrezime(imeIPrezime);
        List<Student> lista;
        model= new ModelTabeleStudent();
        try {
            lista = kontroler.Kontroler.getInstanca().vratiStudente(st);
            
            for (Student s : lista) {
                model.ubaci(s);
            }
            tblStudenti.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnVratiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSveActionPerformed
        try {
            model = new ModelTabeleStudent();
            List<Student> lista = kontroler.Kontroler.getInstanca().vratiSveStudente();
            
            for (Student s : lista) {
                model.ubaci(s);

            }
            tblStudenti.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVratiSveActionPerformed

    private void txtImeIPrezimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeIPrezimeKeyReleased
      
    }//GEN-LAST:event_txtImeIPrezimeKeyReleased

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed

        pripremiDialog(ModForme.izmena);
//        model = new ModelTabeleStudent();
//        tblStudenti.setModel(model);

    }//GEN-LAST:event_btnIzmenaActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        pripremiDialog(ModForme.pregled);
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        pripremiDialog(ModForme.unos);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnIzborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborActionPerformed
        int index = tblStudenti.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red u tabeli");
            return;
        }
        Student s = model.getLista().get(index);
        sesija.Sesija.getInstanca().getMapa().put("trenutniStudent", s);
        (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
        ((FrmForma) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btnIzborActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbor;
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JButton btnUnos;
    private javax.swing.JButton btnVratiSve;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JTable tblStudenti;
    private javax.swing.JTextField txtImeIPrezime;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() {
        model = new ModelTabeleStudent();
        tblStudenti.setModel(model);
    }

    private void pripremiDialog(ModForme modForme) {
        if (modForme != ModForme.unos) {
            int index = tblStudenti.getSelectedRow();

            if (index == -1) {

                JOptionPane.showMessageDialog(this, "Morate izabrati red!");
                return;
            }
            Student s = model.getLista().get(index);
            sesija.Sesija.getInstanca().getMapa().put("trenutniStudent", s);
        }
        
        PnlStudent panel = new PnlStudent(modForme);
        FrmDialog dialog= new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        dialog.setVisible(true);
    }

    public void izaberi() {
        btnIzbor.setVisible(true);
    }

    @Override
    public void popuniPodatke() {
        if(sesija.Sesija.getInstanca().getMapa().get("trenutniStudent")!=null){
        model.getLista().remove(sesija.Sesija.getInstanca().getMapa().get("trenutniStudent"));
        model.ubaci((Student) sesija.Sesija.getInstanca().getMapa().get("trenutniStudent"));
        }
    }
    
}
