/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domen.OpstaDomenskaKlasa;
import domen.Poslodavac;
import domen.RadnoMesto;
import domen.TipRadnogMesta;
import forma.FrmDialog;
import forma.FrmForma;
import forma.IPanel;
import forma.ModForme;
import forma.model.ModelTabeleRM;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Comparator;
import java.util.Date;
import java.util.LinkedList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class PnlPretragaRadnihMesta extends javax.swing.JPanel implements IPanel {

    Poslodavac p;
    ModelTabeleRM model;

    /**
     * Creates new form PnlPretragaRadnihMesta
     */
    public PnlPretragaRadnihMesta() {
        initComponents();
        pripremiFormu();
        btnIzaberi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtSatnica = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cbSlobodnaRM = new javax.swing.JCheckBox();
        cbNapojnica = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTipRM = new javax.swing.JComboBox<>();
        pnlPoslodavac = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        lblKontaktTelefon = new javax.swing.JLabel();
        btnIzborPoslodavca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRM = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnVratiSve = new javax.swing.JButton();
        btnPonistiIzborPoslodavca = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();

        jLabel5.setText("Satnica:");

        jButton3.setText("jButton3");

        cbSlobodnaRM.setText("Prikazi samo slobodna radna mesta");

        cbNapojnica.setText("Prikazi samo radna mesta sa napojnicom");

        jLabel1.setText("Tip radnog mesta:");

        jLabel8.setText("Poslodavac:");

        cbTipRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnlPoslodavac.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o poslodavcu"));

        javax.swing.GroupLayout pnlPoslodavacLayout = new javax.swing.GroupLayout(pnlPoslodavac);
        pnlPoslodavac.setLayout(pnlPoslodavacLayout);
        pnlPoslodavacLayout.setHorizontalGroup(
            pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoslodavacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(lblGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKontaktTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlPoslodavacLayout.setVerticalGroup(
            pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoslodavacLayout.createSequentialGroup()
                .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKontaktTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnIzborPoslodavca.setText("Izbor poslodavca");
        btnIzborPoslodavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborPoslodavcaActionPerformed(evt);
            }
        });

        tblRM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRM);

        btnPretrazi.setText("Pretrazii");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnVratiSve.setText("Vrati sve");
        btnVratiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSveActionPerformed(evt);
            }
        });

        btnPonistiIzborPoslodavca.setText("Ponisti izbor");
        btnPonistiIzborPoslodavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiIzborPoslodavcaActionPerformed(evt);
            }
        });

        btnNovo.setText("Kreiraj novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnDetalji.setText("Prikazi detalje");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzaberi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIzborPoslodavca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipRM, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPonistiIzborPoslodavca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(pnlPoslodavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnVratiSve, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cbNapojnica)
                        .addGap(104, 104, 104)
                        .addComponent(cbSlobodnaRM)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbTipRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(btnIzborPoslodavca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPonistiIzborPoslodavca))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPoslodavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSlobodnaRM)
                            .addComponent(cbNapojnica))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPretrazi)
                            .addComponent(btnVratiSve))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(29, 29, 29)
                        .addComponent(btnDetalji)
                        .addGap(30, 30, 30)
                        .addComponent(btnIzaberi)))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzborPoslodavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborPoslodavcaActionPerformed

        PnlPretragaPoslodavaca panel = new PnlPretragaPoslodavaca();
        panel.izaberi();
        FrmForma forma = new FrmForma(panel);

        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);


    }//GEN-LAST:event_btnIzborPoslodavcaActionPerformed

    private void btnVratiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSveActionPerformed
        try {
            List<RadnoMesto> lista = kontroler.Kontroler.getInstanca().vratiSvaRM();
            model = new ModelTabeleRM();
            for (RadnoMesto s : lista) {
                for (RadnoMesto ss : sesija.Sesija.getInstanca().getRadnaMesta()) {
                    if (ss.equals(s)) {
                        s.setPreostaoBrojIzvrsioca(ss.getPreostaoBrojIzvrsioca());
                        break;
                    }
                }
                model.ubaci(s);

            }
            tblRM.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVratiSveActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        RadnoMesto rm = new RadnoMesto();
        if (p != null) {
            rm.setPoslodavac(p);
        }
        if ((cbTipRM.getSelectedItem() instanceof TipRadnogMesta)) {
            rm.setTipRadnogMesta((TipRadnogMesta) cbTipRM.getSelectedItem());
        }
        if ((cbNapojnica.isSelected())) {
            rm.setMogucaNapojnica(true);
        }
        if (cbSlobodnaRM.isSelected()) {
            rm.setPreostaoBrojIzvrsioca(1);
        }
//        if(dpDatumDo.getSelectedDate()!=null){
//        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
//        Date datum = java.sql.Date.valueOf(format.format(dpDatumDo.getSelectedDate().getTime()));
//        rm.setDatumDo(datum);
//        }
//        if(dpDatumOd.getSelectedDate()!=null){
//        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
//        Date datum1 = java.sql.Date.valueOf(format.format(dpDatumOd.getSelectedDate().getTime()));
//        rm.setDatumOd(datum1);
//        }
        List<RadnoMesto> lista;
        model = new ModelTabeleRM();
        try {

            lista = kontroler.Kontroler.getInstanca().vratiRM(rm);

            for (RadnoMesto s : lista) {
                for (RadnoMesto ss : sesija.Sesija.getInstanca().getRadnaMesta()) {
                    if (ss.equals(s)) {
                        ss.setPreostaoBrojIzvrsioca(ss.getPreostaoBrojIzvrsioca());
                        break;

                    }
                }

                model.ubaci(s);
            }
            tblRM.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(PnlPretragaStudenata.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiIzborPoslodavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiIzborPoslodavcaActionPerformed
        p = null;
        lblNaziv.setText("Naziv kompanije: ");
        lblGrad.setText("Grad: ");
        lblKontaktTelefon.setText("Kontakt telefon: ");
    }//GEN-LAST:event_btnPonistiIzborPoslodavcaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        PnlRadnoMesto panel = new PnlRadnoMesto(ModForme.unos);

//        FrmDialog forma = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        pripremiDialog(ModForme.pregled);
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        int index = tblRM.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red u tabeli");
            return;
        }
        RadnoMesto p1 = model.getLista().get(index);
        if (p1.getDatumOd().before(new Date())) {
            JOptionPane.showMessageDialog(this, "Nije moguce kreirati angazovanje za ovo radno mesto(datumi su prosli)");
            return;

        }
        if (p1.getPreostaoBrojIzvrsioca() == 0) {
            JOptionPane.showMessageDialog(this, "Nije moguce kreirati angazovanje za ovo radno mesto(broj izvrsilaca=0)");
            return;
        }

        sesija.Sesija.getInstanca().getMapa().put("trenutnoRM", p1);
        System.out.println(p1);
        (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
        ((FrmForma) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btnIzaberiActionPerformed

    @Override
    public void popuniPodatke() {
        p = (Poslodavac) sesija.Sesija.getInstanca().getMapa().get("trenutniPoslodavac");
        if (p != null) {
            lblNaziv.setText("Naziv kompanije: " + p.getNazivKompanije());
            lblGrad.setText("Grad: " + p.getGrad().toString());
            lblKontaktTelefon.setText("Kontakt telefon: " + p.getKontaktTelefon());
        }
        if (sesija.Sesija.getInstanca().getMapa().get("trenutnoRM") != null) {

            model.ubaci((RadnoMesto) sesija.Sesija.getInstanca().getMapa().get("trenutnoRM"));
        }
    }

    public void pripremiFormu() {
        model = new ModelTabeleRM();
        tblRM.setModel(model);
        cbTipRM.removeAllItems();
        cbTipRM.addItem("Vrati sve");
        try {
            List<TipRadnogMesta> lista = kontroler.Kontroler.getInstanca().vratiSveTipoveRM();
            lista.sort(Comparator.comparing(TipRadnogMesta::getNazivTipaRadnogMesta));

            for (TipRadnogMesta rm : lista) {
                cbTipRM.addItem(rm);

            }
        } catch (Exception ex) {
            Logger.getLogger(PnlPoslodavac.class.getName()).log(Level.SEVERE, null, ex);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzborPoslodavca;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPonistiIzborPoslodavca;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnVratiSve;
    private javax.swing.JCheckBox cbNapojnica;
    private javax.swing.JCheckBox cbSlobodnaRM;
    private javax.swing.JComboBox<Object> cbTipRM;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblKontaktTelefon;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JPanel pnlPoslodavac;
    private javax.swing.JTable tblRM;
    private javax.swing.JTextField txtSatnica;
    // End of variables declaration//GEN-END:variables

    private void pripremiDialog(ModForme modForme) {
        if (modForme != ModForme.unos) {
            int index = tblRM.getSelectedRow();

            if (index == -1) {

                JOptionPane.showMessageDialog(this, "Morate izabrati red!");
                return;
            }
            RadnoMesto rm = model.getLista().get(index);
            sesija.Sesija.getInstanca().getMapa().put("trenutnoRM", rm);
            PnlRadnoMesto panel = new PnlRadnoMesto(modForme);
            FrmDialog dialog = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
            dialog.setVisible(true);
        }

    }

    public void izaberi() {
        btnIzaberi.setVisible(true);

    }

}
