/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domen.OpstaDomenskaKlasa;
import domen.Poslodavac;
import domen.RadnoMesto;
import domen.TipRadnogMesta;
import forma.FrmDialog;
import forma.FrmForma;
import forma.GlavnaForma;
import forma.IPanel;
import forma.ModForme;
import java.awt.Container;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Comparator;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;

/**
 *
 * @author User
 */
public class PnlRadnoMesto extends javax.swing.JPanel implements IPanel {

    ModForme model;
    Poslodavac p;

    /**
     * Creates new form PnlKreiranjeRM
     */
    public PnlRadnoMesto(ModForme modelForme) {
        model = modelForme;
        initComponents();
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        cbTipRM = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSatnica = new javax.swing.JTextField();
        cbNapojnica = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUkupanBr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPreostaoBr = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        pnlPoslodavac = new javax.swing.JPanel();
        lblNaziv = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        lblKontaktTelefon = new javax.swing.JLabel();
        dpDatumDo = new datechooser.beans.DateChooserCombo();
        dpDatumOd = new datechooser.beans.DateChooserCombo();
        btnIzborPoslodavca = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel1.setText("Tip radnog mesta:");

        cbTipRM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kratak opis:");

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        jLabel3.setText("Datum od:");

        jLabel4.setText("Datum do:");

        cbNapojnica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        jLabel5.setText("Satnica:");

        jLabel6.setText("Moguća napojnica: ");

        lblP.setText("Poslodavac:");

        jLabel8.setText("Ukupan broj izvršioca:");

        txtUkupanBr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUkupanBrKeyReleased(evt);
            }
        });

        jLabel9.setText("Preostao broj izvršioca:");

        txtPreostaoBr.setEditable(false);

        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        pnlPoslodavac.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o poslodavcu"));

        lblNaziv.setText("Naziv kompanije:");

        lblGrad.setText("Grad:");

        lblKontaktTelefon.setText("Kontakt telefon:");

        javax.swing.GroupLayout pnlPoslodavacLayout = new javax.swing.GroupLayout(pnlPoslodavac);
        pnlPoslodavac.setLayout(pnlPoslodavacLayout);
        pnlPoslodavacLayout.setHorizontalGroup(
            pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoslodavacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(lblGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKontaktTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlPoslodavacLayout.setVerticalGroup(
            pnlPoslodavacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPoslodavacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblKontaktTelefon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dpDatumDo.setLocale(new java.util.Locale("sr", "BA", ""));

        dpDatumOd.setLocale(new java.util.Locale("sr", "BA", ""));

        btnIzborPoslodavca.setText("Izbor poslodavca");
        btnIzborPoslodavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborPoslodavcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNapojnica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(dpDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dpDatumDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSatnica))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtUkupanBr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtPreostaoBr, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIzborPoslodavca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipRM, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(342, 342, 342)
                                        .addComponent(btnSacuvaj))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(pnlPoslodavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbTipRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblP)
                            .addComponent(btnIzborPoslodavca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(pnlPoslodavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(204, 204, 204))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(dpDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(dpDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtSatnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbNapojnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUkupanBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPreostaoBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnSacuvaj)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        TipRadnogMesta tip = (TipRadnogMesta) cbTipRM.getSelectedItem();
        String opis = txtOpis.getText();
        double satnica = 0;
        Date datumOd = new Date();
        Date datumDo = new Date();
        try {
            satnica = Double.parseDouble(txtSatnica.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Neodgovarajuci format za ukupan broj izvrsioca!");
            return;

        }
        String napojnica = (String) cbNapojnica.getSelectedItem();
        boolean napojnica1 = false;
        if (napojnica.equals(true)) {
            napojnica1 = true;
        }
        int izvrsioci = 0;
        try {
            izvrsioci = Integer.parseInt(txtUkupanBr.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neodgovarajuci format za ukupan broj izvrsioca!");
            return;
        }
        try {
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            datumOd = java.sql.Date.valueOf(format.format(dpDatumOd.getSelectedDate().getTime()));
            datumDo = java.sql.Date.valueOf(format.format(dpDatumDo.getSelectedDate().getTime()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Morate uneti oba datuma");
            return;

        }
        boolean val = validacija(datumOd, datumDo, izvrsioci, p, satnica);
        if (val) {
            RadnoMesto rm = new RadnoMesto(0, opis, napojnica1, satnica, datumOd, datumDo, izvrsioci, tip, p);
            try {
                String poruka = Kontroler.getInstanca().unesiRM(rm);
                JOptionPane.showMessageDialog(this, poruka);
                sesija.Sesija.getInstanca().getMapa().put("trenutnoRM", rm);
                ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
                if (((SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
                    return;
                }

                (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
            } catch (NullPointerException ex) {
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspesno cuvanje");
//                Logger.getLogger(PnlStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzborPoslodavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborPoslodavcaActionPerformed

        PnlPretragaPoslodavaca panel = new PnlPretragaPoslodavaca();
        panel.izaberi();
//        FrmDialog forma = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);

    }//GEN-LAST:event_btnIzborPoslodavcaActionPerformed

    private void txtUkupanBrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUkupanBrKeyReleased
        txtPreostaoBr.setText(txtUkupanBr.getText());
    }//GEN-LAST:event_txtUkupanBrKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzborPoslodavca;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cbNapojnica;
    private javax.swing.JComboBox<Object> cbTipRM;
    private datechooser.beans.DateChooserCombo dpDatumDo;
    private datechooser.beans.DateChooserCombo dpDatumOd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblKontaktTelefon;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblP;
    private javax.swing.JPanel pnlPoslodavac;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPreostaoBr;
    private javax.swing.JTextField txtSatnica;
    private javax.swing.JTextField txtUkupanBr;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {

        cbTipRM.removeAllItems();
        try {
            List<TipRadnogMesta> lista = kontroler.Kontroler.getInstanca().vratiSveTipoveRM();
            lista.sort(Comparator.comparing(TipRadnogMesta::getNazivTipaRadnogMesta));
            for (TipRadnogMesta rm : lista) {
                cbTipRM.addItem(rm);

            }

        } catch (Exception ex) {
            Logger.getLogger(PnlPoslodavac.class.getName()).log(Level.SEVERE, null, ex);

        }
        if (model == ModForme.pregled) {
            popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutnoRM"));

        }
    }

    @Override
    public void popuniPodatke() {
        p = (Poslodavac) sesija.Sesija.getInstanca().getMapa().get("trenutniPoslodavac");
        if (p != null) {
            lblNaziv.setText("Naziv: " + p.getNazivKompanije());
            lblGrad.setText("Grad: " + p.getGrad().toString());
            lblKontaktTelefon.setText("Kontakt telefon: " + p.getKontaktTelefon());
        }
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        lblP.setVisible(false);
        RadnoMesto rm = (RadnoMesto) odk;
        System.out.println(rm);
        btnSacuvaj.setVisible(false);
        btnIzborPoslodavca.setVisible(false);
        txtOpis.setEditable(false);
        txtPreostaoBr.setEditable(false);
        txtSatnica.setEditable(false);
        txtUkupanBr.setEditable(false);
//            cbNapojnica.setEditable(false);
//            cbTipRM.setEditable(false);

//            dpDatumDo.setEnabled(false);
//            dpDatumOd.setEnabled(false);
        txtOpis.setText(rm.getOpisRadnogMesta());
        txtPreostaoBr.setText(rm.getPreostaoBrojIzvrsioca() + "");
        txtSatnica.setText(rm.getSatnica() + "");
        txtUkupanBr.setText(rm.getUkupanBrIzvrsioca() + "");
        boolean nap = rm.isMogucaNapojnica();

        cbNapojnica.setSelectedItem("" + nap);

        cbTipRM.setSelectedItem(rm.getTipRadnogMesta());

        Poslodavac p = rm.getPoslodavac();
        lblNaziv.setText("Naziv: " + p.getNazivKompanije());
        lblGrad.setText("Grad: " + p.getGrad().toString());
        lblKontaktTelefon.setText("Kontakt telefon: " + p.getKontaktTelefon());
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(rm.getDatumDo());
        dpDatumDo.setSelectedDate(gc);
        gc.setTime(rm.getDatumOd());
        dpDatumOd.setSelectedDate(gc);
    }

    private boolean validacija(Date datumOd, Date datumDo, int izvrsioci, Poslodavac p, double satnica) {
        if (p == null) {
            JOptionPane.showMessageDialog(this, "Morate izabrati poslodavca");
            return false;
        }
        if (izvrsioci <= 0) {
            JOptionPane.showMessageDialog(this, "Broj izvrsioca mora biti veci od 0");
            return false;

        }
        if (satnica <= 0) {
            JOptionPane.showMessageDialog(this, "Satnica mora biti veci od 0");
            return false;

        }
        if (datumDo.before(datumOd)) {
            JOptionPane.showMessageDialog(this, "Datum do mora biti posle datuma od");
            return false;

        }

        return true;
    }

}
