/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import java.awt.Container;
import java.util.LinkedList;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class FrmDialog extends javax.swing.JDialog {

    private IPanel panel;

    /**
     * Creates new form Dialog
     */
    public FrmDialog(java.awt.Frame parent, boolean modal, IPanel panel) {
        super(parent, modal);
        initComponents();
        this.panel = panel;
        postaviPanel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (SwingUtilities.getWindowAncestor(this) instanceof FrmForma) {
            ((FrmForma) SwingUtilities.getWindowAncestor(this)).getPanel().popuniPodatke();
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sesija.Sesija.getInstanca().setRadnaMesta(new LinkedList());
    }//GEN-LAST:event_formWindowClosing

    private void postaviPanel() {
        setContentPane((Container) getPanel());
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * @return the panel
     */
    public IPanel getPanel() {
        return panel;
    }

    /**
     * @param panel the panel to set
     */
    public void setPanel(IPanel panel) {
        this.panel = panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
