/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import forma.panel.PnlRadnoMesto;
import forma.panel.PnlPoslodavac;
import forma.panel.PnlStudent;
import java.awt.Dialog;
import javax.swing.JDialog;

import forma.panel.*;
import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sesija.Sesija;

/**
 *
 * @author User
 */
public class GlavnaForma extends javax.swing.JFrame {

    FrmForma forma;
    FrmDialog dialog;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {

        initComponents();
        lbl1.setText("Dobro došli " + sesija.Sesija.getInstanca().getAgent().getImeIPrezime());
        
        kontroler.Kontroler.getInstanca().setForma(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuStudenti = new javax.swing.JMenu();
        menuPretragaStudenata = new javax.swing.JMenuItem();
        menuUnosStudenta = new javax.swing.JMenuItem();
        menuPoslodavac = new javax.swing.JMenu();
        menuPretragaIzmenaPoslodavca = new javax.swing.JMenuItem();
        menuUnosPoslodavca = new javax.swing.JMenuItem();
        menuRM = new javax.swing.JMenu();
        menuPretragaIzmenaRM = new javax.swing.JMenuItem();
        menuUnosRM = new javax.swing.JMenuItem();
        menuAngazovanja = new javax.swing.JMenu();
        menuPretragaIzmenaAngazovanja = new javax.swing.JMenuItem();
        menuUnosAngazovanja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbl1.setText("jLabel1");

        btnOdjava.setText("Odjavi se");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        menuStudenti.setText("Studenti");

        menuPretragaStudenata.setText("Pretraga/izmena studenata");
        menuPretragaStudenata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaStudenataActionPerformed(evt);
            }
        });
        menuStudenti.add(menuPretragaStudenata);

        menuUnosStudenta.setText("Unos studenta");
        menuUnosStudenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosStudentaActionPerformed(evt);
            }
        });
        menuStudenti.add(menuUnosStudenta);

        jMenuBar1.add(menuStudenti);

        menuPoslodavac.setText("Poslodavci");

        menuPretragaIzmenaPoslodavca.setText("Pretraga poslodavaca");
        menuPretragaIzmenaPoslodavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaIzmenaPoslodavcaActionPerformed(evt);
            }
        });
        menuPoslodavac.add(menuPretragaIzmenaPoslodavca);

        menuUnosPoslodavca.setText("Unos poslodavca");
        menuUnosPoslodavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosPoslodavcaActionPerformed(evt);
            }
        });
        menuPoslodavac.add(menuUnosPoslodavca);

        jMenuBar1.add(menuPoslodavac);

        menuRM.setText("Radna Mesta");

        menuPretragaIzmenaRM.setText("Pretraga radnih mesta");
        menuPretragaIzmenaRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaIzmenaRMActionPerformed(evt);
            }
        });
        menuRM.add(menuPretragaIzmenaRM);

        menuUnosRM.setText("Unos radnog mesta");
        menuUnosRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosRMActionPerformed(evt);
            }
        });
        menuRM.add(menuUnosRM);

        jMenuBar1.add(menuRM);

        menuAngazovanja.setText("Angažovanja");

        menuPretragaIzmenaAngazovanja.setText("Pretraga/izmena angažovanja");
        menuPretragaIzmenaAngazovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaIzmenaAngazovanjaActionPerformed(evt);
            }
        });
        menuAngazovanja.add(menuPretragaIzmenaAngazovanja);

        menuUnosAngazovanja.setText("Unos angažovanja");
        menuUnosAngazovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosAngazovanjaActionPerformed(evt);
            }
        });
        menuAngazovanja.add(menuUnosAngazovanja);

        jMenuBar1.add(menuAngazovanja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btnOdjava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOdjava)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPretragaStudenataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaStudenataActionPerformed
        PnlPretragaStudenata panel = new PnlPretragaStudenata();
        forma = new FrmForma(panel);
        forma.setVisible(true);

    }//GEN-LAST:event_menuPretragaStudenataActionPerformed

    private void menuUnosStudentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosStudentaActionPerformed

        PnlStudent ps = new PnlStudent(ModForme.unos);
        dialog = new FrmDialog(this, true, ps);
        dialog.setVisible(true);

    }//GEN-LAST:event_menuUnosStudentaActionPerformed

    private void menuPretragaIzmenaPoslodavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaIzmenaPoslodavcaActionPerformed
        PnlPretragaPoslodavaca panel = new PnlPretragaPoslodavaca();
        forma = new FrmForma(panel);
        forma.setVisible(true);
    }//GEN-LAST:event_menuPretragaIzmenaPoslodavcaActionPerformed

    private void menuUnosPoslodavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosPoslodavcaActionPerformed

        PnlPoslodavac ps = new PnlPoslodavac(ModForme.unos);
        dialog = new FrmDialog(this, true, ps);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuUnosPoslodavcaActionPerformed

    private void menuPretragaIzmenaAngazovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaIzmenaAngazovanjaActionPerformed
        PnlPretragaAngazovanja ps = new PnlPretragaAngazovanja();
        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_menuPretragaIzmenaAngazovanjaActionPerformed

    private void menuUnosRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosRMActionPerformed

        PnlRadnoMesto ps = new PnlRadnoMesto(ModForme.unos);
        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_menuUnosRMActionPerformed

    private void menuPretragaIzmenaRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaIzmenaRMActionPerformed
        PnlPretragaRadnihMesta ps = new PnlPretragaRadnihMesta();
        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_menuPretragaIzmenaRMActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        try {
            String odgovor = kontroler.Kontroler.getInstanca().odjavaSaSistema(Sesija.getInstanca().getAgent());
            JOptionPane.showMessageDialog(this, odgovor);
            FormaZaPrijavljivanje form = new FormaZaPrijavljivanje();
            form.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void menuUnosAngazovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosAngazovanjaActionPerformed
        PnlAngazovanje ps = new PnlAngazovanje(ModForme.unos);

        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_menuUnosAngazovanjaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        try {
//            String odgovor = kontroler.Kontroler.getInstanca().odjavaSaSistema(Sesija.getInstanca().getAgent());
//            JOptionPane.showMessageDialog(this, odgovor);
//            FormaZaPrijavljivanje form = new FormaZaPrijavljivanje();
//            form.setVisible(true);
//            dispose();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjava;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JMenu menuAngazovanja;
    private javax.swing.JMenu menuPoslodavac;
    private javax.swing.JMenuItem menuPretragaIzmenaAngazovanja;
    private javax.swing.JMenuItem menuPretragaIzmenaPoslodavca;
    private javax.swing.JMenuItem menuPretragaIzmenaRM;
    private javax.swing.JMenuItem menuPretragaStudenata;
    private javax.swing.JMenu menuRM;
    private javax.swing.JMenu menuStudenti;
    private javax.swing.JMenuItem menuUnosAngazovanja;
    private javax.swing.JMenuItem menuUnosPoslodavca;
    private javax.swing.JMenuItem menuUnosRM;
    private javax.swing.JMenuItem menuUnosStudenta;
    // End of variables declaration//GEN-END:variables
}
